<Project>
  <ItemDefinitionGroup>
    <Reference>
      <Private>false</Private>
    </Reference>
  </ItemDefinitionGroup>

  <ItemGroup>
    <Reference Include="$(GameDir)\MelonLoader\net6\MelonLoader.dll" />
    <Reference Include="$(GameDir)\MelonLoader\net6\0Harmony.dll" />
    <Reference Include="$(GameDir)\MelonLoader\net6\Il2CppInterop.Runtime.dll" />
    <Reference Include="$(GameDir)\MelonLoader\net6\Il2CppInterop.Common.dll" />
    <Reference Include="$(GameDir)\MelonLoader\net6\Il2CppInterop.HarmonySupport.dll" />
    <Reference Include="$(InteropRefDir)\*.dll" />
  </ItemGroup>

  <Target Name="CopyDllToMods" AfterTargets="Build">
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(GameDir)\Mods" />
  </Target>
</Project>
